//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Microsoft.SqlServer.DatabaseInstaller {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/2009/10/adventure-works/database-manifest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2009/10/adventure-works/database-manifest", IsNullable=false)]
    public partial class DatabaseManifest {
        
        private string installerTitleField;
        
        private string defaultScriptInstallPathField;
        
        private string requiredMajorVersionField;
        
        private string requiredMinorVersionField;
        
        private string buildNumberField;
        
        private DatabaseManifestDatabase[] databaseField;
        
        /// <remarks/>
        public string InstallerTitle {
            get {
                return this.installerTitleField;
            }
            set {
                this.installerTitleField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultScriptInstallPath {
            get {
                return this.defaultScriptInstallPathField;
            }
            set {
                this.defaultScriptInstallPathField = value;
            }
        }
        
        /// <remarks/>
        public string RequiredMajorVersion {
            get {
                return this.requiredMajorVersionField;
            }
            set {
                this.requiredMajorVersionField = value;
            }
        }
        
        /// <remarks/>
        public string RequiredMinorVersion {
            get {
                return this.requiredMinorVersionField;
            }
            set {
                this.requiredMinorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BuildNumber {
            get {
                return this.buildNumberField;
            }
            set {
                this.buildNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Database")]
        public DatabaseManifestDatabase[] Database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/2009/10/adventure-works/database-manifest")]
    public partial class DatabaseManifestDatabase {
        
        private string databaseNameField;
        
        private string prettyNameField;
        
        private string sourceDatabaseScriptRelativePathField;
        
        private string[] targetDatabaseFileField;
        
        private object[] targetDatabaseAdditionaiDirectoryField;
        
        private bool isOLAPRequiredField;
        
        private bool isFTSRequiredField;
        
        private bool isFileStreamRequiredField;
        
        private bool isEnterpriseRequiredField;
        
        private bool isStandardRequiredField;
        
        private int approximateMessageCountField;
        
        private bool approximateMessageCountFieldSpecified;
        
        /// <remarks/>
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        public string PrettyName {
            get {
                return this.prettyNameField;
            }
            set {
                this.prettyNameField = value;
            }
        }
        
        /// <remarks/>
        public string SourceDatabaseScriptRelativePath {
            get {
                return this.sourceDatabaseScriptRelativePathField;
            }
            set {
                this.sourceDatabaseScriptRelativePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetDatabaseFile")]
        public string[] TargetDatabaseFile {
            get {
                return this.targetDatabaseFileField;
            }
            set {
                this.targetDatabaseFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetDatabaseAdditionaiDirectory")]
        public object[] TargetDatabaseAdditionaiDirectory {
            get {
                return this.targetDatabaseAdditionaiDirectoryField;
            }
            set {
                this.targetDatabaseAdditionaiDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOLAPRequired {
            get {
                return this.isOLAPRequiredField;
            }
            set {
                this.isOLAPRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFTSRequired {
            get {
                return this.isFTSRequiredField;
            }
            set {
                this.isFTSRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFileStreamRequired {
            get {
                return this.isFileStreamRequiredField;
            }
            set {
                this.isFileStreamRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnterpriseRequired {
            get {
                return this.isEnterpriseRequiredField;
            }
            set {
                this.isEnterpriseRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsStandardRequired {
            get {
                return this.isStandardRequiredField;
            }
            set {
                this.isStandardRequiredField = value;
            }
        }
        
        /// <remarks/>
        public int ApproximateMessageCount {
            get {
                return this.approximateMessageCountField;
            }
            set {
                this.approximateMessageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApproximateMessageCountSpecified {
            get {
                return this.approximateMessageCountFieldSpecified;
            }
            set {
                this.approximateMessageCountFieldSpecified = value;
            }
        }
    }
}
