//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.DatabaseInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.DatabaseInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.50.
        /// </summary>
        internal static string CompatibleVersions {
            get {
                return ResourceManager.GetString("CompatibleVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;DatabaseManifestSchema&quot;
        ///    targetNamespace=&quot;http://schemas.microsoft.com/sqlserver/2009/10/adventure-works/database-manifest&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/sqlserver/2009/10/adventure-works/database-manifest&quot;
        ///    xmlns:mstns=&quot;http://schemas.microsoft.com/sqlserver/2009/10/adventure-works/database-manifest&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;DatabaseManifest&quot;&gt;
        ///    &lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseManifestSchema {
            get {
                return ResourceManager.GetString("DatabaseManifestSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdventureWorks2008_SR4.exe.
        /// </summary>
        internal static string InstallerName {
            get {
                return ResourceManager.GetString("InstallerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdventureWorks 2008 Community Sample Databases SR4.
        /// </summary>
        internal static string InstallerTitle {
            get {
                return ResourceManager.GetString("InstallerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2008 and 2008R2.
        /// </summary>
        internal static string PrettyCompatibleSqlVersions {
            get {
                return ResourceManager.GetString("PrettyCompatibleSqlVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0.
        /// </summary>
        internal static string PrimaryVersion {
            get {
                return ResourceManager.GetString("PrimaryVersion", resourceCulture);
            }
        }
    }
}
